// AUTO-GENERATED by scripts/fetch-online-backgrounds.mjs — do not edit by hand.
// Populated when the online-theme fetcher runs (needs UNSPLASH_ACCESS_KEY).
// Until then it is empty and only the bundled images in
// public/images/backgrounds/ are used.
export const ONLINE_BACKGROUND_IMAGES: string[] = [];
