// AUTO-GENERATED by scripts/gen-backgrounds.mjs — do not edit by hand.
export const BACKGROUND_IMAGES: string[] = [
  "/images/backgrounds/bg-01.jpg",
  "/images/backgrounds/bg-02.jpg",
  "/images/backgrounds/bg-03.jpg",
  "/images/backgrounds/bg-04.jpg",
  "/images/backgrounds/bg-05.jpg",
  "/images/backgrounds/bg-06.jpg",
  "/images/backgrounds/bg-07.jpg",
  "/images/backgrounds/bg-08.jpg",
  "/images/backgrounds/bg-09.jpg",
  "/images/backgrounds/bg-10.jpg",
  "/images/backgrounds/bg-11.jpg",
  "/images/backgrounds/bg-12.jpg",
  "/images/backgrounds/bg-13.jpg",
  "/images/backgrounds/bg-14.jpg",
  "/images/backgrounds/bg-15.webp",
  "/images/backgrounds/bg-16.jpg",
  "/images/backgrounds/bg-17.jpg",
  "/images/backgrounds/bg-18.jpg"
];
