// AUTO-GENERATED by scripts/gen-backgrounds.mjs — do not edit by hand.
export const BACKGROUND_IMAGES: string[] = [
  "/images/backgrounds/bg-01.svg",
  "/images/backgrounds/bg-02.svg",
  "/images/backgrounds/bg-03.svg"
];
