import { Document, Page, View, Text } from "@react-pdf/renderer";
import { styles, DocumentHeader, Field, DocFooter } from "./shared";

export type DailyYardStockReportData = {
  docNumber: string;
  qrDataUrl: string;
  generatedAt: string;
  reportDate: string;
  byType: { code: string; count: number }[];
  reeferCount: number;
  totalStock: number;
  empty: number;
  full: number;
  underPti: number;
  underRepair: number;
  readyForRelease: number;
  generatedBy: string;
};

export function DailyYardStockReportPdf(data: DailyYardStockReportData) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <DocumentHeader
          docTitle="Daily Yard Inventory Report"
          docNumber={data.docNumber}
          qrDataUrl={data.qrDataUrl}
          generatedAt={data.generatedAt}
        />

        <Field label="Report Date" value={data.reportDate} />

        <Text style={styles.sectionTitle}>Summary</Text>
        <View style={styles.grid}>
          {data.byType.map((t) => (
            <Field key={t.code} label={`${t.code} Containers`} value={String(t.count)} />
          ))}
          <Field label="Reefers" value={String(data.reeferCount)} />
        </View>
        <View style={{ marginTop: 6 }}>
          <Field label="Total Stock" value={String(data.totalStock)} full />
        </View>

        <Text style={styles.sectionTitle}>Status Breakdown</Text>
        <View style={styles.grid}>
          <Field label="Empty" value={String(data.empty)} />
          <Field label="Full" value={String(data.full)} />
          <Field label="Under PTI" value={String(data.underPti)} />
          <Field label="Under Repair" value={String(data.underRepair)} />
          <Field label="Ready for Release" value={String(data.readyForRelease)} />
        </View>

        <Field label="Generated By" value={data.generatedBy} />

        <DocFooter page={1} totalPages={1} />
      </Page>
    </Document>
  );
}
